import { createRouter } from "@tanstack/react-router";
// routeTree.gen.ts is generated by the TanStack Start Vite plugin at build/dev time.
import { routeTree } from "./routeTree.gen";

export function getRouter() {
  return createRouter({
    routeTree,
    defaultPreload: "intent",
    scrollRestoration: true,
  });
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
